/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as PapersIndexRouteImport } from './routes/papers.index'
import { Route as PapersIdRouteImport } from './routes/papers.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIndexRoute = PapersIndexRouteImport.update({
  id: '/papers/',
  path: '/papers/',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersIdRoute = PapersIdRouteImport.update({
  id: '/papers/$id',
  path: '/papers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/media': typeof MediaRoute
  '/meetings': typeof MeetingsRoute
  '/notes': typeof NotesRoute
  '/roadmap': typeof RoadmapRoute
  '/tasks': typeof TasksRoute
  '/voice': typeof VoiceRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/': typeof PapersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/media': typeof MediaRoute
  '/meetings': typeof MeetingsRoute
  '/notes': typeof NotesRoute
  '/roadmap': typeof RoadmapRoute
  '/tasks': typeof TasksRoute
  '/voice': typeof VoiceRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers': typeof PapersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/media': typeof MediaRoute
  '/meetings': typeof MeetingsRoute
  '/notes': typeof NotesRoute
  '/roadmap': typeof RoadmapRoute
  '/tasks': typeof TasksRoute
  '/voice': typeof VoiceRoute
  '/papers/$id': typeof PapersIdRoute
  '/papers/': typeof PapersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/media'
    | '/meetings'
    | '/notes'
    | '/roadmap'
    | '/tasks'
    | '/voice'
    | '/papers/$id'
    | '/papers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/media'
    | '/meetings'
    | '/notes'
    | '/roadmap'
    | '/tasks'
    | '/voice'
    | '/papers/$id'
    | '/papers'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/media'
    | '/meetings'
    | '/notes'
    | '/roadmap'
    | '/tasks'
    | '/voice'
    | '/papers/$id'
    | '/papers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  MediaRoute: typeof MediaRoute
  MeetingsRoute: typeof MeetingsRoute
  NotesRoute: typeof NotesRoute
  RoadmapRoute: typeof RoadmapRoute
  TasksRoute: typeof TasksRoute
  VoiceRoute: typeof VoiceRoute
  PapersIdRoute: typeof PapersIdRoute
  PapersIndexRoute: typeof PapersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/': {
      id: '/papers/'
      path: '/papers'
      fullPath: '/papers/'
      preLoaderRoute: typeof PapersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$id': {
      id: '/papers/$id'
      path: '/papers/$id'
      fullPath: '/papers/$id'
      preLoaderRoute: typeof PapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  MediaRoute: MediaRoute,
  MeetingsRoute: MeetingsRoute,
  NotesRoute: NotesRoute,
  RoadmapRoute: RoadmapRoute,
  TasksRoute: TasksRoute,
  VoiceRoute: VoiceRoute,
  PapersIdRoute: PapersIdRoute,
  PapersIndexRoute: PapersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
